################################################################################
# FrameBuffer Driver for Display
#
#
################################################################################

######################################
# MT6572/82/92 are lagecy projects, will be removed, so have no common part
# any more. Use belows for all when legacy projects are removed
# obj-$(CONFIG_MTK_FB) += common/
obj-$(CONFIG_MTK_FB) += $(subst ",,$(CONFIG_MTK_PLATFORM))/

obj-$(CONFIG_ARCH_MT6795) += common/
